theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false  
  logo:
    header: '/assets/images/logo-blanc.svg'
    footer: '/assets/images/logo-blanc.svg'